
# Loop constraints
directive set /des_check/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /des_check/core/core:rlp/main CSTEPS_FROM {{. == 17} {.. == 0}}

# IO operation constraints
directive set /des_check/core/core:rlp/main/input:io_read(input:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/key:io_read(key:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/inv_init_perm_res:io_write(return:rsc.@) CSTEPS_FROM {{.. == 16}}

# Sync operation constraints

# Real operation constraints
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#1 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#2 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#3 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#4 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#5 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#6 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#7 CSTEPS_FROM {{.. == 1}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#8 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#9 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#10 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#11 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#12 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#13 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#14 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#15 CSTEPS_FROM {{.. == 2}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#16 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#17 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#18 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#19 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#20 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#21 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#22 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#23 CSTEPS_FROM {{.. == 3}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#24 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#25 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#26 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#27 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#28 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#29 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#30 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#31 CSTEPS_FROM {{.. == 4}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#32 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#33 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#34 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#35 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#36 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#37 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#38 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#39 CSTEPS_FROM {{.. == 5}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#40 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#41 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#42 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#43 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#44 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#45 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#46 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#47 CSTEPS_FROM {{.. == 6}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#48 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#49 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#50 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#51 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#52 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#53 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#54 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#55 CSTEPS_FROM {{.. == 7}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#56 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#57 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#58 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#59 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#60 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#61 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#62 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#63 CSTEPS_FROM {{.. == 8}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#64 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#65 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#66 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#67 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#68 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#69 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#70 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#71 CSTEPS_FROM {{.. == 9}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#72 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#73 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#74 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#75 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#76 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#77 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#78 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#79 CSTEPS_FROM {{.. == 10}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#80 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#81 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#82 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#83 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#84 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#85 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#86 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#87 CSTEPS_FROM {{.. == 11}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#88 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#89 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#90 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#91 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#92 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#93 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#94 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#95 CSTEPS_FROM {{.. == 12}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#96 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#97 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#98 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#99 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#100 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#101 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#102 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#103 CSTEPS_FROM {{.. == 13}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#104 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#105 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#106 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#107 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#108 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#109 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#110 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#111 CSTEPS_FROM {{.. == 14}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#112 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#113 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#114 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#115 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#116 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#117 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#118 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#119 CSTEPS_FROM {{.. == 15}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#120 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#121 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#122 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#123 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#124 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#125 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#126 CSTEPS_FROM {{.. == 16}}
directive set /des_check/core/core:rlp/main/operator&<8,false>#1:read_rom(S.rom_map_1)#127 CSTEPS_FROM {{.. == 16}}

# Probe constraints
